- app/models/artist.rb
- app/models/favorite_item.rb
- app/models/item.rb
- app/models/user.rb
James and I added associations and basic validations to the core models
> Model associations and validations

- Gemfile
- Gemfile.lock
Cloudinary set up -
created .env file and added .env* to .gitignore
added cloudinary gem to Gemfile
> Cloudinary

- .gitignore
- app/controllers/users_controller.rb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
Added route and added controller for user
Added show action in controller and view
> adding users controller, show route, action and view

- .gitignore
- Gemfile.lock
- app/controllers/artists_controller.rb
- app/controllers/users_controller.rb
- app/views/artists/index.html.erb
- app/views/artists/show.html.erb
- config/routes.rb
- test/controllers/artists_controller_test.rb
Added controller files for artists table, and defined index and show methods.
Added view files for artists index and show
> Add artists controller

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
Added 5 highlight colours to colors.scss and added header, body and artist fonts to fonts.scss
> Colour scheme and Fonts

- Gemfile
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/index.html.erb
- app/views/items/new.html.erb
- config/routes.rb
- test/controllers/items_controller_test.rb
Added:
gem for simple form
items controller
show, index, new and create actions
All routes for current items paths.
basic views for above paths
> Items controller

- app/controllers/favorite_items_controller.rb
- config/routes.rb
- test/controllers/favorite_items_controller_test.rb
generated controller for favorite items, and defined the create method for it.
there are no specified view routes for this model, so no views were created.
the route has been created, however it needs to nested inside the items routes which james is in the process of making, we will resolve this conflict as and when it occurs.
> Favorite item controller

- db/migrate/20210608150207_add_names_to_user.rb
- db/migrate/20210608150240_add_address_to_user.rb
- db/schema.rb
Added migrations to user model for:
first_name
last_name
address
> adding name and address to user model

- app/controllers/favorites_controller.rb
- config/routes.rb
- test/controllers/favorites_controller_test.rb
generated favorites controller and route
> configured route for favorites, and generated favorites controller

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/controllers/favorites_controller.rb
- app/views/favorites/index.html.erb
- config/routes.rb
corrected a few typo errors that rails was addressing, and then fixed a few bootstrap color syntax errors, this all in tandem with making the basic favorites-index view file
> Add favorites index

- app/models/item.rb
- app/views/items/new.html.erb
Added category validations to item
added select dropdown to new item form
> Category validations

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
think this footer looks nice now, easy to make changes though
> Footer update

- app/controllers/items_controller.rb
- app/views/items/_filter.html.erb
- app/views/items/index_creation.html.erb
- db/seeds.rb
Adding index create page with filter function. Filter says there's no items in the correct category if there aren't.
> Index create

- app/assets/stylesheets/components/_form.scss
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/items/new.html.erb
just quickly applied formatting to login screens
> login forms

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/bookings/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- Would be better for the buttons to each be a different colour, but it's taking too long right now, will come back to it.
> Bookings show

- app/assets/stylesheets/components/_fill_button.scss
- app/assets/stylesheets/components/_index.scss
- app/views/artists/show.html.erb
- app/views/users/show.html.erb
starting formatting for artist_show page
> starting formatting for artist show page

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/bookings/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_donation_new.html.erb
We can access the creation and decoration paths from the HP!
> added creation and decoration routes

- app/views/shared/_navbar.html.erb
Profile option added to dropdown list when you click the avatar in the navbar
- Added bookings as well but can't get the link to work yet.. will raise a ticket tomorrow
-
> Added profile link to dropdown in navbar

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
changes to cards to fit design and a bit more spacing
> Homepage changes 1

- app/views/bookings/show.html.erb
- app/views/items/index_decoration.html.erb
- app/views/items/show.html.erb
- app/views/shared/_decoration_new.html.erb
rerouted so that when you select an item from the index-decorate, it'll take you to the items show, with a booking form below and then to the confirmation page
> Bookings conf

- app/assets/stylesheets/components/_card-item.scss
- app/assets/stylesheets/components/_text.scss
- app/views/shared/_creation_new.html.erb
- app/views/shared/_donation_new.html.erb
Overall improvement of the bookings new pages. The user can now upload between 0 - 3 pictures (ideally 2 max) without the page looking too weird 😬
> Bookings new alignment

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/items_controller.rb
- app/views/artists/show.html.erb
- app/views/items/index_decoration.html.erb
- app/views/items/show.html.erb
- app/views/items/toggle_favorite.js.erb
a few changes to artist avatar and show page css
item show page has some placeholders now for us to do some more advanced css later if we wish
> Favorites show pages

- app/assets/stylesheets/components/_alert.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_sweetalert.js
- app/views/items/show.html.erb
- package.json
- yarn.lock
- Added Sweet Alert to 'Add to basket' btn on item show - decorate.
> Sweet alert

- app/assets/stylesheets/components/_button.scss
- app/views/favorites/index.html.erb
- app/views/items/index_creation.html.erb
- app/views/items/index_decoration.html.erb
- app/views/items/show.html.erb
- app/views/pages/home.html.erb
- Added Turbolinks: false to items show page so that the 'add to basket' button works without having to hard refresh the page
- Button fixed so that it doesn't take up whole page
- Button colour changed to yellow
> Turbolinks

- app/assets/stylesheets/components/_form.scss
Altered button weight to be slightly more bold
> Button font bold

- app/views/items/new.html.erb
Tell us more about the furniture, we'll come and collect it for free....etc
> Change description on items new donate

- app/controllers/basket_items_controller.rb
- app/views/baskets/show.html.erb
- app/views/items/show.html.erb
> Fix basket

- app/assets/stylesheets/components/_navbar.scss
Adding image shake to logo and a bit of padding to move up a little
> adding image shake to logo

- app/views/items/_filter.html.erb
- app/views/items/index_decoration.html.erb
- Removed bed from create and decorate index filter
-
> removed bed from filter

- app/views/baskets/show.html.erb
- app/views/payments/new.html.erb
> Checkout page

- app/assets/stylesheets/components/_confetti.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/baskets_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/confetti.js
- app/views/baskets/success.html.erb
-confetti
-order summary on page
> Order confirmation page

- db/seeds.rb
- seed file with custom artists and users
- updated seed with better pictures, only 1 January Fisher, and Natasha's picture
> final seed
